// Functions to interact with the icpp_llama2 canister
import { canisterId, createActor } from 'DeclarationsCanisterLlama2'

const IC_HOST_URL = process.env.IC_HOST_URL

export async function doSubmit({
  authClient,
  actorRef,
  chatNew,
  setActorRef,
  setChatNew,
  setPromptRef,
  text,
  setChatOutputText,
  setChatDisplay,
}) {
  console.log('entered llama2.js doSubmit ')
  console.log('chatNew : ', chatNew)
  let actor_ = actorRef.current
  if (chatNew) {
    console.log('Creating identity ')
    const identity = await authClient.getIdentity()
    console.log('Creating actor ')
    actor_ = createActor(canisterId, {
      agentOptions: {
        identity,
        host: IC_HOST_URL,
      },
    })
    setActorRef(actor_)
  }

  try {
    // Call llama2 canister to check on health
    // Force a re-render, showing the WaitAnimation
    setChatDisplay('WaitAnimation')
    console.log('Calling actor_.health ')
    const responseHealth = await actor_.health()
    console.log('llama2 canister health: ', responseHealth)

    if (responseHealth) {
      console.log('llama2 canister is healthy: ', responseHealth)

      console.log('Calling actor_.ready ')
      const responseReady = await actor_.ready()
      console.log('llama2 canister ready: ', responseReady)

      if (responseReady) {
        setPromptRef(text)
        if (chatNew) {
          // This will force a re-render, switching from ChatSelectModel to ChatOutput
          setChatNew(false)
          // Force a re-render, showing the ChatOutput
          setChatDisplay('ChatOutput')
        }
        // This will force a re-render of the ChatOutput component
        setChatOutputText(
          "(HARD-CODED, NOT YET GENERATED BY LLM: Once upon a time, my teddy, Mr. Fluffles, went on a big adventure in the backyard. He climbed Mount Sofa, swam the Deep Blue Puddle, and even flew in the air when I threw him. We had a picnic with cookies, but then, oh no! Mr. Fluffles got cookie crumbs on him. So, we had a bath together with lots of bubbles. Mommy said, 'It’s bedtime.' But we weren’t sleepy, so we told each other stories. Mr. Fluffles whispered a secret, 'You're my best friend.' And I whispered back, 'Forever and ever.' Then, we closed our eyes. Goodnight."
        )
      } else {
        throw new Error(`LLM canister is not ready`)
      }
    } else {
      throw new Error(`LLM canister is not healthy`)
    }
  } catch (error) {
    console.error(error)
    // Force a re-render, showing the ChatOutput
    setChatDisplay('CanisterError')
  }
}
